### ISSUE TITLE
Use with Gamekeeper

### ISSUE THREAD

**Issue by jonathancolledge** [Xyrus2000/ChessBridge#2]
Have you seen this: http://www.digitalgametechnology.com/index.php/support1/dgt-software/unsupported/14-gamekeeper?mavikthumbnails_display_ratio=1.5

It works with ChessBridge and Chessmaster Grandmaster Edition and is awesome! Thanks. I just followed the instructions in the Gamekeeper Readme after setting up ChessBridge - ChessBridge still works and I think ensures that the Gamekeeper works (Gamekeeper isn't supposed to work with Grandmaster Edition, I've not tested it on its own, but it definitely works with ChessBridge). The ChessBridge application gets renamed to RealEngine.exe and the ProxyEngine from Gamekeeper gets renamed to TheKing350_64.exe or TheKing350.exe depending on whether CM is set to 64 bit in the user ini file in the data>users folder.

**Comment by Xyrus2000** [comment]
I'm a little confused here. Are you reporting an issue? It sounds like from your description that my app works for this, which is nice to hear considering I wrote this five years ago. :)

**Comment by jonathancolledge** [comment]
Yes, very sorry, not an issue. I just wanted to point out how awesome Chessbridge is for still making this work.

**Comment by Xyrus2000** [comment]
Cool. I didn't necessarily write it for that purpose but I'm glad it works for you. At least some besides me has made use of the software. :D
