### ISSUE TITLE
Compilation steps

### ISSUE THREAD

**Issue by bprijadi** [Xyrus2000/ChessBridge#3]
Would love to use this. But don't know what files to and how to compile this in my Windows 10 machine. Wish there is a "for dummies" version of the readme file :)

**Comment by Xyrus2000** [comment]
Compilation is the easy part. Manually setting up everything to work will require some technical know how. I've tried to explain it as plainly as possible but there is no "make it work" button. :)

For compilation, all you should need is either MS visual studio (community edition) or Sharp Develop. Double click on the solution file (.sln) and it should load it up. Once loaded you can select "Compile" and it should build.

However, keep in mind this code is pretty old so it may need to be tweaked.

**Comment by bprijadi** [comment]
Many thanks for this. I have searched and tried with wb2uci and uci2wb
which did its job, but did not port 100% The Kiing 3.50 64 bit.
Polyglot had its issues as well. All these for almost 3 weeks now :).
Hopefully ChessBridge will port better!
Thank you very much.

Budana from Jakarta, Indonesia.

A Chessmaster heavy user (now back to it after watching Netflik's "The
Queens Gambit")

**Comment by bprijadi** [comment]
Btw. I downloaded Arena 3.5.1 Windows and failed to find the Polyglot file
:(

**Comment by jonathancolledge** [comment]
Here is a polyglot file for using Stockfish in Chessmaster with instructions for where to get polyglot. It'll need some tweaking, but does work without. I haven't tried CM in Arena. 

https://github.com/jonathancolledge/Polyglot.ini-for-Chessmaster-Grandmaster-Edition

**Comment by bprijadi** [comment]
Thank you much!

That's why I could not find Polyglot because my Winboard is the one here
http://www.playwitharena.de/

Let me play around with it. Thank you once again

Budana
